version: '3.3'
services:
  timescaledb:
    container_name: timescaledb
    image: 'timescale/timescaledb:latest-pg14'
    ports:
      - '5433:5432'
    volumes:
      # - '/mnt/hdd1/Workspace/timescaledb:/var/lib/postgresql/data'
      - '/home/adhikasp/Workplace/timescaledb-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=password
      - TZ=Asia/Jakarta
  
  mysql8:
    container_name: mysql-8
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Jakarta
      